Information to detail.
ferrous-systems/espressif-trainings pull request #88
Opened 2022-08-04 15:02 UTC by Dajamante

Points to be added to the driver exercise 
NEED TO ADD BAUD RATE

2022-09-08 15:20 UTC, BriocheBerlin requested changes
Probably the whole solution folder needs to go. Also it seems that in the `hard` exercise most formatting is broken.

2022-09-08 15:20 UTC, BriocheBerlin commented on book/src/04_3_3_i2c.md
> +```rust
Following all the formatting of the examples is broken. It seems doing `\```rust` is not necessary when 
`\<Details>` and `\<Summary>` is used.

2022-09-08 15:20 UTC, BriocheBerlin commented on book/src/04_3_3_i2c.md
> +        let icm42670p = ICM42670P { i2c, address };
It looks like this in `lib.rs`. Here shouldn't it be only `Ok(Self { i2c, address })`?

2022-09-08 15:20 UTC, BriocheBerlin commented on book/src/04_3_3_i2c.md
> +- Returning a value with MSB and LSB is done by shifting MSB values, and OR LSB values.
Same as in `easy`: what is MSB and LSB?

2022-09-08 15:20 UTC, BriocheBerlin commented on book/src/04_3_3_i2c.md
> +(maybe from `from_be_bytes[GYRO_data_X1, GYRO_DATA_X2] is better)
Same as in `easy`: this seems like a note to self.

2022-09-09 10:51 UTC, Mirabellensaft commented
I have removed all the hidden code in the hard version because there was no clean and easy way to do it. People just have to check in the corresponding section in the easy version. This also removes tons of duplicate information \o/. I have found a way to fix this for newer mdbook versions though.

2022-09-09 12:56 UTC, BriocheBerlin approved these changes

2022-09-09 12:57 UTC, BriocheBerlin commented
Not sure why Docker fails... Otherwise looks good 👍

2022-09-09 14:30 UTC, merged